name: A-Stock-Auto-Robot

on:
  workflow_dispatch: 
  schedule:
    - cron: '40 1 * * 1-5'
    - cron: '30 3 * * 1-5'
    - cron: '0 6 * * 1-5'
    - cron: '0 7 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install akshare pandas openpyxl requests numpy

    - name: Run Robot
      run: python stock_robot.py

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # 强制删除旧索引并添加新文件
        git add index.xlsx || true
        git commit -m "Update Report" || echo "No changes"
        git push origin main
