name: A-Stock-Auto-Robot
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install -r requirements.txt
      - name: Run
        run: python stock_robot.py
      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.xlsx
          git commit -m "📊 实时报告更新 $(date)" || exit 0
          git push origin main
